### ISSUE TITLE
Data for the examples

### ISSUE THREAD

**Issue by labdmitriy** [alicezheng/feature-engineering-book#1]
#Hello,

Jupyter notebooks have a links to data files in local directories, but there are no directories in the repository, so it is unable to run notebooks, what is correct way to run these notebooks, need to manually download data files?

Thank you.

**Comment by alicezheng** [comment]
Hey, we don't own the rights to the data. You'll have to download them from the urls given in the book. I'll make a note of this in the repo as well. Sorry about the confusion.

**Comment by davidmillsap** [comment]
You can use the latest yelp dataset challenge (#8)  It comes as a TAR file, with another TAR file in it, thats full of JSON.  So untar it once, add a "*.tar" to the extracted file to your dataset folder.  The following function will get you going with the Books Lessons and the new Yelp dataset.

import json
import tarfile
import os

repo = r'C:\Datasets'
dataset = r'yelp_dataset.tar'

def fetchData(repo, dataset):
    # Reads Json from a *.tar file and returns a dataframe
    tgz_file = os.path.join(repo, dataset)
    tar = tarfile.open(tgz_file)
    f = tar.extractfile("dataset/business.json")
    df = pd.DataFrame([json.loads(x) for x in f.readlines()])
    tar.close()
    f.close()
    return df

biz_df = fetchData(repo, dataset)`
