### ISSUE TITLE
关于数据集问题

### ISSUE THREAD

**Issue by 471417367** [alicezheng/feature-engineering-book#13]
您好，关于书中使用的数据集，可否告知出处，在书中没有找到数据集的链接。

**Comment by pvalue31415936** [comment]
https://www.yelp.com/dataset/download

**Comment by nicholaschen-cn** [comment]
请问第9章的数据集在哪里下载？谢谢

**Comment by sondywoo** [comment]
> 请问第9章的数据集在哪里下载？谢谢

https://www.microsoft.com/en-us/research/project/open-academic-graph/
Link given in the notebook

**Comment by Kidron-Hou** [comment]
chap2 https://www.kaggle.com/yelp-dataset/yelp-dataset?select=yelp_academic_dataset_business.json

**Comment by Kidron-Hou** [comment]
kaggle上已解压的yelp数据集
https://www.kaggle.com/yelp-dataset/yelp-dataset?select=yelp_academic_dataset_business.json

**Comment by Kevin1466** [comment]
一点一点地找，挺麻烦的

**Comment by alicezheng** [comment]
Hey folks, sorry about the trouble with the datasets. Since we do not own the data, we cannot distribute them. So your best course of action is to search for them online. I understand it's troublesome, but we do not have a better solution.

您好，抱歉由于数据版权问题我们没有权力提供下载。所有数据都应该能在网上找到，望谅解。
