### ISSUE TITLE
Dataset needing

### ISSUE THREAD

**Issue by HYLCHF** [alicezheng/feature-engineering-book#17]
Hi everyone, 
there are many datasets used in this book, but I didn't see source page links attached in the content. Could someone share those dataset please? Thank you!

**Comment by Kevin1466** [comment]
Have you got it? If so, can you share?

**Comment by alicezheng** [comment]
Hi folks, sorry about the long delay in my response. We do not own the rights to those datasets, hence we can not include them in this repo. We provided links to the datasets where we could, but those may be out of date now as well. I think the best course of action is to search for those datasets and download them from scratch. Sorry, we did not have a good solution to the problem.

**Comment by HorusJiang** [comment]
> Hi folks, sorry about the long delay in my response. We do not own the rights to those datasets, hence we can not include them in this repo. We provided links to the datasets where we could, but those may be out of date now as well. I think the best course of action is to search for those datasets and download them from scratch. Sorry, we did not have a good solution to the problem.

Thank you，Alice!

**Comment by HorusJiang** [comment]
> Have you got it? If so, can you share?

Not yet, I am gonna looking for it by myself
