### ISSUE TITLE
Ordering of the topics

### ISSUE THREAD

**Issue by divyanshu16** [alicezheng/feature-engineering-book#3]
Could you please provide the order in which one should go through the topics?

**Comment by alicezheng** [comment]
Hi there, do you mean an ordering of the notebooks in this repo? This repo accompanies the book "[Feature Engineering for Machine Learning](https://www.amazon.com/Feature-Engineering-Machine-Learning-Principles/dp/1491953241/)". I recommend following the ordering in the book. Here's the chapter list:
1. Introduction
2. Fancy Tricks with Simple Numbers
3. Text Data: Flatten, Filtering, and Chunking
4. The Effects of Feature Scaling: From Bag-of-Words to Tf-Idf
5. Categorical Variables: Counting Eggs in the Age of Robotic Chickens
6. Dimensionality Reduction: Squashing the Data Pancake with PCA
7. Non-Linear Featurization and Model Stacking
8. Automating the Featurizer: Image Feature Extraction and Deep Learning
9. Back to the Feature: Putting it All Together

**Comment by divyanshu16** [comment]
Actually, I meant the ordering of topics in the repo so that even if someone has not gone through the book can go through it in the order of difficulty.

**Comment by amcasari** [comment]
I've proposed a naming schema to clarify what notebooks match up with chapters + examples. Our chapters were designed to build, so hope this helps!

Sent PR for review.
